/*************************************************************************************************
 * Copyright 2022-2024 Theai, Inc. dba Inworld AI
 *
 * Use of this source code is governed by the Inworld.ai Software Development Kit License Agreement
 * that can be found in the LICENSE.md file or at https://www.inworld.ai/sdk-license
 *************************************************************************************************/

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Inworld.Entities.LLM
{
	// Chat completion message.
	public class ChoiceMessage 
	{
	// The contents of the chunk message.
		public string content;
		// The tool calls generated by the model, such as function calls.
		public List<ToolCall> tool_calls;
		// The role of the author of this message.
		public MessageRole role;
	}
	public class Choice
	{
		[JsonConverter(typeof(StringEnumConverter))]
		public FinishReason finish_reason; // The reason the model stopped generating tokens.
		public int index; // The index of the choice in the list of choices.
	}
	public class ChatChoice : Choice
	{
		public ChoiceMessage message; // A chat completion message generated by the model.
	}
	public class TextChoice : Choice
	{
		public string text; // Generated text.
	}
}
